### ISSUE TITLE
`../vocab` required

### ISSUE THREAD

**Issue by XTM233** [tgaddair/quora-duplicate-question-detector#2]
Hello!
When I tried to run eval.py, it showed that there should be a `../vocab` path present to build vocabulary.
Could you tell what is that exactly?
Thanks.

**Comment by houzhenzhen** [comment]
Hello 
Can you tell me  which  TensorFlow and Python version you were running?

**Comment by XTM233** [comment]
Hello
The issue is solved already but still thanks for your reply!

**Comment by houzhenzhen** [comment]
@XTM233 
Hello
I also meet the same question with you ,can you tell me how you deal it?
